### PR TITLE
Add Playground page Closes #160

### LINKED ISSUE #160: Add Playground component/page
# Feature request 🚀

Playground component/page is play the component online

### Expected:
  - No breaking changes

### Examples:

Refer to [Zeit Playground](https://zeit.co/design/playground)

### PR DESCRIPTION
**Pull request by yuler**
## PR Checklist

- [x] Fix linting errors
- [x] Label has been added

## Change information

resolved #160

### CODE REVIEW

**Comment by yuler** [comment]
Close #160

**Comment by unix** [comment]
And are you chinese, we can chat online?

**Comment by yuler** [comment]
@unix Yes, How can I contact you

**Comment by unix** [comment]
@yuler 
https://jq.qq.com/?_wv=1027&k=54J48nl

**Pull request closed without merging**
